src/App.vue: fixed a warning.
The warning read:

ElementPlusError: [el-radio] [API] label act as value is about to be deprecated in version 3.0.0, please use value instead.